version: '3.7'
services:
  whoami:
    image: jwilder/whoami

  oauth2-proxy:
    image: quay.io/oauth2-proxy/oauth2-proxy:v6.1.0
    environment:
      OAUTH2_PROXY_UPSTREAMS: http://whoami:8000
      OAUTH2_PROXY_HTTP_ADDRESS: 0.0.0.0:4180
      OAUTH2_PROXY_PROVIDER: oidc
      OAUTH2_PROXY_PROVIDER_DISPLAY_NAME: My OIDC Provider
      OAUTH2_PROXY_CLIENT_ID: bdc3aaae60458ac4842375b6b5fa5f69be12a4f33b21c4184cdeaddce54a3cb2
      OAUTH2_PROXY_CLIENT_SECRET: fcd0922e490066bdfc653831ee0cc6dcbaca544ae9c030e9ba4ae0744fb142da
      OAUTH2_PROXY_REDIRECT_URL: http://127.0.0.1:4180/oauth2/callback
      OAUTH2_PROXY_OIDC_ISSUER_URL: https://gitlab.example.com
      OAUTH2_PROXY_COOKIE_SECURE: "false"
      OAUTH2_PROXY_EMAIL_DOMAINS: "*"
      OAUTH2_PROXY_COOKIE_SECRET: "ELaagnC-VvnDPLByDAS8qA=="
    ports:
      - "4180:4180"

networks:
  default:
    name: poc-oauth2-proxy
